#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Spark_Hand

#include "Basic.hpp"

#include "AnimBP_Spark_Hand_classes.hpp"
#include "AnimBP_Spark_Hand_parameters.hpp"


namespace SDK
{

// Function AnimBP_Spark_Hand.AnimBP_Spark_Hand_C.ExecuteUbergraph_AnimBP_Spark_Hand
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Spark_Hand_C::ExecuteUbergraph_AnimBP_Spark_Hand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Spark_Hand_C", "ExecuteUbergraph_AnimBP_Spark_Hand");

	Params::AnimBP_Spark_Hand_C_ExecuteUbergraph_AnimBP_Spark_Hand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

