#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CaptionsTools

#include "Basic.hpp"

#include "Enum_Language_structs.hpp"
#include "captions_structs.hpp"


namespace SDK::Params
{

// Function BP_CaptionsTools.BP_CaptionsTools_C.ExecuteUbergraph_BP_CaptionsTools
// 0x0300 (0x0300 - 0x0000)
struct BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable1;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue1;                  // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable1;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate1;             // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue1;         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable3;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable3;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable4;                    // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_Language                                 Temp_byte_Variable;                                // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable4;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue4;                  // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable5;                    // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable5;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue5;                  // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        K2Node_CustomEvent_SoundAttached;                  // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_Sound;                          // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsTips;                         // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_TipsSoundLoopCount;             // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_TipsSoundLoopDelay;             // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_TipsDisplayTime;                // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_AlwaysShow;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMer2GameInstance_C*                    K2Node_DynamicCast_AsMer_2Game_Instance;           // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue6;                  // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item;                           // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameOverTips_C*                        CallFunc_Array_Get_Item1;                          // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue1;                // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue1;                 // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E3[0x5];                                       // 0x00E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item2;                          // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item3;                          // 0x0108(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue3;                // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue1;                     // 0x0115(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_116[0x2];                                      // 0x0116(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1;              // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item4;                          // 0x0128(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameOverTips_C*                        CallFunc_Array_Get_Item5;                          // 0x0130(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x3];                                      // 0x0139(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue4;                // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue3;                 // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_142[0x2];                                      // 0x0142(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UGameOverTips_C*>                CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0148(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue4;                     // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTaskOwnerInterface> CallFunc_TaskWaitDelay_TaskOwner_CastInput;  // 0x0160(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UGameplayTask_WaitDelay*                CallFunc_TaskWaitDelay_ReturnValue;                // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue5;                     // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTaskOwnerInterface> CallFunc_TaskWaitDelay_TaskOwner1_CastInput; // 0x0180(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UGameplayTask_WaitDelay*                CallFunc_TaskWaitDelay_ReturnValue1;               // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue6;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTaskOwnerInterface> CallFunc_TaskWaitDelay_TaskOwner2_CastInput; // 0x01A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UGameplayTask_WaitDelay*                CallFunc_TaskWaitDelay_ReturnValue2;               // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue7;                     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate2;             // 0x01C0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue8;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_Pause;                          // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D2[0x6];                                      // 0x01D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct Fcaptions                              CallFunc_GetDataTableRowFromName_OutRow;           // 0x01D8(0x00B8)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default;                             // 0x0298(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue9;                     // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A9[0x7];                                      // 0x02A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_ParseIntoArray_ReturnValue;               // 0x02B0(0x0010)(ZeroConstructor, ReferenceParm)
	int32                                         Temp_int_Variable1;                                // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C4[0x4];                                      // 0x02C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item6;                          // 0x02C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameOverTips_C*                        CallFunc_Array_Get_Item7;                          // 0x02D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue10;                    // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D9[0x3];                                      // 0x02D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue5;                // 0x02DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue4;                 // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue11;                    // 0x02E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E2[0x6];                                      // 0x02E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameOverTips_C*                        CallFunc_Array_Get_Item8;                          // 0x02E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameOverTips_C*                        CallFunc_Array_Get_Item9;                          // 0x02F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue6;                // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue12;                    // 0x02FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue5;                 // 0x02FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools) == 0x000008, "Wrong alignment on BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools");
static_assert(sizeof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools) == 0x000300, "Wrong size on BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, EntryPoint) == 0x000000, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable1) == 0x000010, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue1) == 0x000028, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable2) == 0x00002C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue2) == 0x000030, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable1) == 0x000034, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CreateDelegate_OutputDelegate1) == 0x000038, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000048, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable2) == 0x00004C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_EqualEqual_ByteByte_ReturnValue1) == 0x000050, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_EqualEqual_ByteByte_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable3) == 0x000054, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable3) == 0x000058, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue3) == 0x00005C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable4) == 0x000060, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_byte_Variable) == 0x000064, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable4) == 0x000068, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue4) == 0x00006C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Array_Index_Variable5) == 0x000070, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Array_Index_Variable5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Loop_Counter_Variable5) == 0x000074, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Loop_Counter_Variable5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue5) == 0x000078, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_Event_DeltaSeconds) == 0x00007C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_GetGameInstance_ReturnValue) == 0x000080, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_SoundAttached) == 0x000088, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_SoundAttached' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_Sound) == 0x000090, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_Sound' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_IsTips) == 0x000098, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_IsTips' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_TipsSoundLoopCount) == 0x00009C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_TipsSoundLoopCount' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_TipsSoundLoopDelay) == 0x0000A0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_TipsSoundLoopDelay' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_TipsDisplayTime) == 0x0000A4, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_TipsDisplayTime' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_AlwaysShow) == 0x0000A8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_AlwaysShow' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_DynamicCast_AsMer_2Game_Instance) == 0x0000B0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_DynamicCast_AsMer_2Game_Instance' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_DynamicCast_bSuccess) == 0x0000B8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_IntInt_ReturnValue6) == 0x0000BC, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_IntInt_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x0000C0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item) == 0x0000C8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item1) == 0x0000D0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue) == 0x0000D8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue1) == 0x0000DC, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue) == 0x0000E0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue1) == 0x0000E1, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000E2, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item2) == 0x0000E8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue) == 0x0000F0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000F4, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_FTrunc_ReturnValue) == 0x0000F8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue2) == 0x0000FC, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Clamp_ReturnValue) == 0x000100, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item3) == 0x000108, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue3) == 0x000110, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue2) == 0x000114, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue1) == 0x000115, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Subtract_IntInt_ReturnValue) == 0x000118, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Add_FloatFloat_ReturnValue1) == 0x00011C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Add_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Greater_IntInt_ReturnValue) == 0x000120, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item4) == 0x000128, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item5) == 0x000130, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue2) == 0x000138, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue4) == 0x00013C, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue3) == 0x000140, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue3) == 0x000141, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Variable) == 0x000144, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000148, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue4) == 0x000158, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_TaskOwner_CastInput) == 0x000160, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_TaskOwner_CastInput' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_ReturnValue) == 0x000170, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue5) == 0x000178, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_TaskOwner1_CastInput) == 0x000180, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_TaskOwner1_CastInput' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_ReturnValue1) == 0x000190, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue6) == 0x000198, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_TaskOwner2_CastInput) == 0x0001A0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_TaskOwner2_CastInput' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_TaskWaitDelay_ReturnValue2) == 0x0001B0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_TaskWaitDelay_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue7) == 0x0001B8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue7' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CreateDelegate_OutputDelegate2) == 0x0001C0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue8) == 0x0001D0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue8' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_CustomEvent_Pause) == 0x0001D1, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_CustomEvent_Pause' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_GetDataTableRowFromName_OutRow) == 0x0001D8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000290, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, K2Node_Select_Default) == 0x000298, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue9) == 0x0002A8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue9' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_ParseIntoArray_ReturnValue) == 0x0002B0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_ParseIntoArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, Temp_int_Variable1) == 0x0002C0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::Temp_int_Variable1' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item6) == 0x0002C8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item6' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item7) == 0x0002D0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item7' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue10) == 0x0002D8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue10' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue5) == 0x0002DC, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue4) == 0x0002E0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue11) == 0x0002E1, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue11' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item8) == 0x0002E8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item8' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Get_Item9) == 0x0002F0, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Get_Item9' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Array_Length_ReturnValue6) == 0x0002F8, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Array_Length_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_IsValid_ReturnValue12) == 0x0002FC, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_IsValid_ReturnValue12' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools, CallFunc_Less_IntInt_ReturnValue5) == 0x0002FD, "Member 'BP_CaptionsTools_C_ExecuteUbergraph_BP_CaptionsTools::CallFunc_Less_IntInt_ReturnValue5' has a wrong offset!");

// Function BP_CaptionsTools.BP_CaptionsTools_C.PauseSound
// 0x0001 (0x0001 - 0x0000)
struct BP_CaptionsTools_C_PauseSound final
{
public:
	bool                                          Pause;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CaptionsTools_C_PauseSound) == 0x000001, "Wrong alignment on BP_CaptionsTools_C_PauseSound");
static_assert(sizeof(BP_CaptionsTools_C_PauseSound) == 0x000001, "Wrong size on BP_CaptionsTools_C_PauseSound");
static_assert(offsetof(BP_CaptionsTools_C_PauseSound, Pause) == 0x000000, "Member 'BP_CaptionsTools_C_PauseSound::Pause' has a wrong offset!");

// Function BP_CaptionsTools.BP_CaptionsTools_C.DisplayCaptions
// 0x0028 (0x0028 - 0x0000)
struct BP_CaptionsTools_C_DisplayCaptions final
{
public:
	class USceneComponent*                        SoundAttached_0;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Sound;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsTips;                                            // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TipsSoundLoopCount_0;                              // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TipsSoundLoopDelay_0;                              // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TipsDisplayTime;                                   // 0x001C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AlwaysShow;                                        // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CaptionsTools_C_DisplayCaptions) == 0x000008, "Wrong alignment on BP_CaptionsTools_C_DisplayCaptions");
static_assert(sizeof(BP_CaptionsTools_C_DisplayCaptions) == 0x000028, "Wrong size on BP_CaptionsTools_C_DisplayCaptions");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, SoundAttached_0) == 0x000000, "Member 'BP_CaptionsTools_C_DisplayCaptions::SoundAttached_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, Sound) == 0x000008, "Member 'BP_CaptionsTools_C_DisplayCaptions::Sound' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, IsTips) == 0x000010, "Member 'BP_CaptionsTools_C_DisplayCaptions::IsTips' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, TipsSoundLoopCount_0) == 0x000014, "Member 'BP_CaptionsTools_C_DisplayCaptions::TipsSoundLoopCount_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, TipsSoundLoopDelay_0) == 0x000018, "Member 'BP_CaptionsTools_C_DisplayCaptions::TipsSoundLoopDelay_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, TipsDisplayTime) == 0x00001C, "Member 'BP_CaptionsTools_C_DisplayCaptions::TipsDisplayTime' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_DisplayCaptions, AlwaysShow) == 0x000020, "Member 'BP_CaptionsTools_C_DisplayCaptions::AlwaysShow' has a wrong offset!");

// Function BP_CaptionsTools.BP_CaptionsTools_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_CaptionsTools_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CaptionsTools_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_CaptionsTools_C_ReceiveTick");
static_assert(sizeof(BP_CaptionsTools_C_ReceiveTick) == 0x000004, "Wrong size on BP_CaptionsTools_C_ReceiveTick");
static_assert(offsetof(BP_CaptionsTools_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_CaptionsTools_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_CaptionsTools.BP_CaptionsTools_C.SpawnSound
// 0x0018 (0x0018 - 0x0000)
struct BP_CaptionsTools_C_SpawnSound final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSound2D_ReturnValue;                 // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CaptionsTools_C_SpawnSound) == 0x000008, "Wrong alignment on BP_CaptionsTools_C_SpawnSound");
static_assert(sizeof(BP_CaptionsTools_C_SpawnSound) == 0x000018, "Wrong size on BP_CaptionsTools_C_SpawnSound");
static_assert(offsetof(BP_CaptionsTools_C_SpawnSound, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'BP_CaptionsTools_C_SpawnSound::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnSound, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000008, "Member 'BP_CaptionsTools_C_SpawnSound::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnSound, CallFunc_SpawnSound2D_ReturnValue) == 0x000010, "Member 'BP_CaptionsTools_C_SpawnSound::CallFunc_SpawnSound2D_ReturnValue' has a wrong offset!");

// Function BP_CaptionsTools.BP_CaptionsTools_C.SpawnCaptions
// 0x0030 (0x0030 - 0x0000)
struct BP_CaptionsTools_C_SpawnCaptions final
{
public:
	class USceneComponent*                        SoundAttached_0;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Sound;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsTips;                                            // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TipsSoundLoopCount_0;                              // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TipsSoundLoopDelay_0;                              // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TipsDisplayTime;                                   // 0x001C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AlwaysShow;                                        // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SoundDuration;                                     // 0x0024(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CaptionsTools_C_SpawnCaptions) == 0x000008, "Wrong alignment on BP_CaptionsTools_C_SpawnCaptions");
static_assert(sizeof(BP_CaptionsTools_C_SpawnCaptions) == 0x000030, "Wrong size on BP_CaptionsTools_C_SpawnCaptions");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, SoundAttached_0) == 0x000000, "Member 'BP_CaptionsTools_C_SpawnCaptions::SoundAttached_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, Sound) == 0x000008, "Member 'BP_CaptionsTools_C_SpawnCaptions::Sound' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, IsTips) == 0x000010, "Member 'BP_CaptionsTools_C_SpawnCaptions::IsTips' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, TipsSoundLoopCount_0) == 0x000014, "Member 'BP_CaptionsTools_C_SpawnCaptions::TipsSoundLoopCount_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, TipsSoundLoopDelay_0) == 0x000018, "Member 'BP_CaptionsTools_C_SpawnCaptions::TipsSoundLoopDelay_0' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, TipsDisplayTime) == 0x00001C, "Member 'BP_CaptionsTools_C_SpawnCaptions::TipsDisplayTime' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, AlwaysShow) == 0x000020, "Member 'BP_CaptionsTools_C_SpawnCaptions::AlwaysShow' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, SoundDuration) == 0x000024, "Member 'BP_CaptionsTools_C_SpawnCaptions::SoundDuration' has a wrong offset!");
static_assert(offsetof(BP_CaptionsTools_C_SpawnCaptions, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'BP_CaptionsTools_C_SpawnCaptions::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

