#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeadlyBulletSettings

#include "Basic.hpp"

#include "BP_DeadlyBulletSettings_classes.hpp"
#include "BP_DeadlyBulletSettings_parameters.hpp"


namespace SDK
{

// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.ExecuteUbergraph_BP_DeadlyBulletSettings
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::ExecuteUbergraph_BP_DeadlyBulletSettings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "ExecuteUbergraph_BP_DeadlyBulletSettings");

	Params::BP_DeadlyBulletSettings_C_ExecuteUbergraph_BP_DeadlyBulletSettings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.OnHitBonus
// (BlueprintCallable, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::OnHitBonus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "OnHitBonus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.SetCustomDifficult
// (BlueprintCallable, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::SetCustomDifficult()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "SetCustomDifficult");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "ReceiveTick");

	Params::BP_DeadlyBulletSettings_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.IsAllowDeadlyBullet
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DeadlyBulletSettings_C::IsAllowDeadlyBullet(float Rate, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "IsAllowDeadlyBullet");

	Params::BP_DeadlyBulletSettings_C_IsAllowDeadlyBullet Parms{};

	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.AddDeadlyBullet
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsDeadly                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DeadlyBulletSettings_C::AddDeadlyBullet(bool IsDeadly)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "AddDeadlyBullet");

	Params::BP_DeadlyBulletSettings_C_AddDeadlyBullet Parms{};

	Parms.IsDeadly = IsDeadly;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.AddNormalBullet
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::AddNormalBullet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "AddNormalBullet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.GetGenerateItem
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EItemTypes*                             Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::GetGenerateItem(EItemTypes* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "GetGenerateItem");

	Params::BP_DeadlyBulletSettings_C_GetGenerateItem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.RequireGenerateItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           FromWho                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EItemTypes                              Special                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor**                          ActorReturn                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::RequireGenerateItem(class AActor* FromWho, const struct FVector& Location, EItemTypes Special, class AActor** ActorReturn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "RequireGenerateItem");

	Params::BP_DeadlyBulletSettings_C_RequireGenerateItem Parms{};

	Parms.FromWho = FromWho;
	Parms.Location = std::move(Location);
	Parms.Special = Special;

	UObject::ProcessEvent(Func, &Parms);

	if (ActorReturn != nullptr)
		*ActorReturn = Parms.ActorReturn;
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.SetSettings
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStruct_DeadlyBulletSettings&Settings_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::SetSettings(const struct FStruct_DeadlyBulletSettings& Settings_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "SetSettings");

	Params::BP_DeadlyBulletSettings_C_SetSettings Parms{};

	Parms.Settings_0 = std::move(Settings_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.CountWaves
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DeadlyBulletSettings_C::CountWaves()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "CountWaves");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeadlyBulletSettings.BP_DeadlyBulletSettings_C.GetSettings
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FStruct_DeadlyBulletSettings*    Settings_0                                             (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeadlyBulletSettings_C::GetSettings(struct FStruct_DeadlyBulletSettings* Settings_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeadlyBulletSettings_C", "GetSettings");

	Params::BP_DeadlyBulletSettings_C_GetSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Settings_0 != nullptr)
		*Settings_0 = std::move(Parms.Settings_0);
}

}

