#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lv2_CarPost

#include "Basic.hpp"

#include "BP_Lv2_CarPost_classes.hpp"


namespace SDK
{

// Function BP_Lv2_CarPost.BP_Lv2_CarPost_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Lv2_CarPost_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_CarPost_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

