#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LV2_Giacontroller

#include "Basic.hpp"

#include "BP_LV2_Giacontroller_classes.hpp"
#include "BP_LV2_Giacontroller_parameters.hpp"


namespace SDK
{

// Function BP_LV2_Giacontroller.BP_LV2_Giacontroller_C.ExecuteUbergraph_BP_LV2_Giacontroller
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LV2_Giacontroller_C::ExecuteUbergraph_BP_LV2_Giacontroller(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LV2_Giacontroller_C", "ExecuteUbergraph_BP_LV2_Giacontroller");

	Params::BP_LV2_Giacontroller_C_ExecuteUbergraph_BP_LV2_Giacontroller Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LV2_Giacontroller.BP_LV2_Giacontroller_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LV2_Giacontroller_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LV2_Giacontroller_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LV2_Giacontroller.BP_LV2_Giacontroller_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_LV2_Giacontroller_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LV2_Giacontroller_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

