#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lv2_HiddenGia

#include "Basic.hpp"

#include "BP_Lv2_NPCBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lv2_HiddenGia.BP_Lv2_HiddenGia_C
// 0x0000 (0x0880 - 0x0880)
class ABP_Lv2_HiddenGia_C final : public ABP_Lv2_NPCBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Lv2_HiddenGia_C">();
	}
	static class ABP_Lv2_HiddenGia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lv2_HiddenGia_C>();
	}
};
static_assert(alignof(ABP_Lv2_HiddenGia_C) == 0x000010, "Wrong alignment on ABP_Lv2_HiddenGia_C");
static_assert(sizeof(ABP_Lv2_HiddenGia_C) == 0x000880, "Wrong size on ABP_Lv2_HiddenGia_C");

}

