#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lv2_Wpn_AAC

#include "Basic.hpp"

#include "BP_Lv2_Wpn_AAC_classes.hpp"
#include "BP_Lv2_Wpn_AAC_parameters.hpp"


namespace SDK
{

// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.ExecuteUbergraph_BP_Lv2_Wpn_AAC
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lv2_Wpn_AAC_C::ExecuteUbergraph_BP_Lv2_Wpn_AAC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "ExecuteUbergraph_BP_Lv2_Wpn_AAC");

	Params::BP_Lv2_Wpn_AAC_C_ExecuteUbergraph_BP_Lv2_Wpn_AAC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.DisplayTexture
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Lv2_Wpn_AAC_C::DisplayTexture(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "DisplayTexture");

	Params::BP_Lv2_Wpn_AAC_C_DisplayTexture Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.AttachScope
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_Lv2_Wpn_AAC_C::AttachScope()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "AttachScope");

	Params::BP_Lv2_Wpn_AAC_C_AttachScope Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lv2_Wpn_AAC_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "ReceiveTick");

	Params::BP_Lv2_Wpn_AAC_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Lv2_Wpn_AAC_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lv2_Wpn_AAC.BP_Lv2_Wpn_AAC_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Lv2_Wpn_AAC_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lv2_Wpn_AAC_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

