#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RestrictWall

#include "Basic.hpp"

#include "BP_RestrictWall_classes.hpp"
#include "BP_RestrictWall_parameters.hpp"


namespace SDK
{

// Function BP_RestrictWall.BP_RestrictWall_C.ExecuteUbergraph_BP_RestrictWall
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RestrictWall_C::ExecuteUbergraph_BP_RestrictWall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RestrictWall_C", "ExecuteUbergraph_BP_RestrictWall");

	Params::BP_RestrictWall_C_ExecuteUbergraph_BP_RestrictWall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RestrictWall.BP_RestrictWall_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RestrictWall_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RestrictWall_C", "ReceiveTick");

	Params::BP_RestrictWall_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RestrictWall.BP_RestrictWall_C.ActiveCollision
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Active                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_RestrictWall_C::ActiveCollision(bool Active)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RestrictWall_C", "ActiveCollision");

	Params::BP_RestrictWall_C_ActiveCollision Parms{};

	Parms.Active = Active;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RestrictWall.BP_RestrictWall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RestrictWall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RestrictWall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RestrictWall.BP_RestrictWall_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_RestrictWall_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RestrictWall_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

