#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_Follow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTTask_Follow.BTTask_Follow_C
// 0x0030 (0x00D0 - 0x00A0)
class UBTTask_Follow_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 SteerAngle;                                        // 0x00A8(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BTTask_Follow(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTTask_Follow_C">();
	}
	static class UBTTask_Follow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTTask_Follow_C>();
	}
};
static_assert(alignof(UBTTask_Follow_C) == 0x000008, "Wrong alignment on UBTTask_Follow_C");
static_assert(sizeof(UBTTask_Follow_C) == 0x0000D0, "Wrong size on UBTTask_Follow_C");
static_assert(offsetof(UBTTask_Follow_C, UberGraphFrame) == 0x0000A0, "Member 'UBTTask_Follow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBTTask_Follow_C, SteerAngle) == 0x0000A8, "Member 'UBTTask_Follow_C::SteerAngle' has a wrong offset!");

}

