#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CsvModule

#include "Basic.hpp"


namespace SDK::Params
{

// Function CsvModule.CsvHelper.CsvStrConvertToJsonStr
// 0x0020 (0x0020 - 0x0000)
struct CsvHelper_CsvStrConvertToJsonStr final
{
public:
	class FString                                 csvRaw;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CsvHelper_CsvStrConvertToJsonStr) == 0x000008, "Wrong alignment on CsvHelper_CsvStrConvertToJsonStr");
static_assert(sizeof(CsvHelper_CsvStrConvertToJsonStr) == 0x000020, "Wrong size on CsvHelper_CsvStrConvertToJsonStr");
static_assert(offsetof(CsvHelper_CsvStrConvertToJsonStr, csvRaw) == 0x000000, "Member 'CsvHelper_CsvStrConvertToJsonStr::csvRaw' has a wrong offset!");
static_assert(offsetof(CsvHelper_CsvStrConvertToJsonStr, ReturnValue) == 0x000010, "Member 'CsvHelper_CsvStrConvertToJsonStr::ReturnValue' has a wrong offset!");

}

