#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EQS_GetTargetActorContext

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EQS_GetTargetActorContext.EQS_GetTargetActorContext_C
// 0x0000 (0x0030 - 0x0030)
class UEQS_GetTargetActorContext_C final : public UEnvQueryContext_BlueprintBase
{
public:
	void ProvideSingleActor(class UObject* QuerierObject, class AActor* QuerierActor, class AActor** ResultingActor) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EQS_GetTargetActorContext_C">();
	}
	static class UEQS_GetTargetActorContext_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEQS_GetTargetActorContext_C>();
	}
};
static_assert(alignof(UEQS_GetTargetActorContext_C) == 0x000008, "Wrong alignment on UEQS_GetTargetActorContext_C");
static_assert(sizeof(UEQS_GetTargetActorContext_C) == 0x000030, "Wrong size on UEQS_GetTargetActorContext_C");

}

