#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lv4_AttackCarBase

#include "Basic.hpp"

#include "Lv4_AttackCarBase_classes.hpp"
#include "Lv4_AttackCarBase_parameters.hpp"


namespace SDK
{

// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.ExecuteUbergraph_Lv4-AttackCarBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALv4_AttackCarBase_C::ExecuteUbergraph_Lv4_AttackCarBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "ExecuteUbergraph_Lv4-AttackCarBase");

	Params::Lv4_AttackCarBase_C_ExecuteUbergraph_Lv4_AttackCarBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.CarDead
// (BlueprintCallable, BlueprintEvent)

void ALv4_AttackCarBase_C::CarDead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "CarDead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.BndEvt__Mesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ALv4_AttackCarBase_C::BndEvt__Mesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "BndEvt__Mesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::Lv4_AttackCarBase_C_BndEvt__Mesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.OnDead_事件_0
// (BlueprintCallable, BlueprintEvent)

void ALv4_AttackCarBase_C::OnDead_事件_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "OnDead_事件_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.XYTargetLocation
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void ALv4_AttackCarBase_C::XYTargetLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "XYTargetLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALv4_AttackCarBase_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "ReceiveTick");

	Params::Lv4_AttackCarBase_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALv4_AttackCarBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Lv4-AttackCarBase.Lv4-AttackCarBase_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ALv4_AttackCarBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Lv4-AttackCarBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

