#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lv4_AttackCarController1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lv4-AttackCarController1.Lv4-AttackCarController1_C
// 0x0008 (0x0440 - 0x0438)
class ALv4_AttackCarController1_C final : public AAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0438(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Lv4_AttackCarController1(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Lv4-AttackCarController1_C">();
	}
	static class ALv4_AttackCarController1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALv4_AttackCarController1_C>();
	}
};
static_assert(alignof(ALv4_AttackCarController1_C) == 0x000008, "Wrong alignment on ALv4_AttackCarController1_C");
static_assert(sizeof(ALv4_AttackCarController1_C) == 0x000440, "Wrong size on ALv4_AttackCarController1_C");
static_assert(offsetof(ALv4_AttackCarController1_C, UberGraphFrame) == 0x000438, "Member 'ALv4_AttackCarController1_C::UberGraphFrame' has a wrong offset!");

}

