#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mer2AchievementComponent

#include "Basic.hpp"

#include "Mer2AchievementComponent_classes.hpp"
#include "Mer2AchievementComponent_parameters.hpp"


namespace SDK
{

// Function Mer2AchievementComponent.Mer2AchievementComponent_C.ExecuteUbergraph_Mer2AchievementComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMer2AchievementComponent_C::ExecuteUbergraph_Mer2AchievementComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "ExecuteUbergraph_Mer2AchievementComponent");

	Params::Mer2AchievementComponent_C_ExecuteUbergraph_Mer2AchievementComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UMer2AchievementComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.UnlockSteamAchievement
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_Achievement                        Achievement                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMer2AchievementComponent_C::UnlockSteamAchievement(class APlayerController* PlayerController, Enum_Achievement Achievement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "UnlockSteamAchievement");

	Params::Mer2AchievementComponent_C_UnlockSteamAchievement Parms{};

	Parms.PlayerController = PlayerController;
	Parms.Achievement = Achievement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnSuccess_3A1532A449CA8E12C725E29D9CD57262
// (BlueprintCallable, BlueprintEvent)

void UMer2AchievementComponent_C::OnSuccess_3A1532A449CA8E12C725E29D9CD57262()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnSuccess_3A1532A449CA8E12C725E29D9CD57262");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnFailure_3A1532A449CA8E12C725E29D9CD57262
// (BlueprintCallable, BlueprintEvent)

void UMer2AchievementComponent_C::OnFailure_3A1532A449CA8E12C725E29D9CD57262()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnFailure_3A1532A449CA8E12C725E29D9CD57262");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnSuccess_A7F272754A56CDF721E29285B42B7853
// (BlueprintCallable, BlueprintEvent)

void UMer2AchievementComponent_C::OnSuccess_A7F272754A56CDF721E29285B42B7853()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnSuccess_A7F272754A56CDF721E29285B42B7853");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnFailure_A7F272754A56CDF721E29285B42B7853
// (BlueprintCallable, BlueprintEvent)

void UMer2AchievementComponent_C::OnFailure_A7F272754A56CDF721E29285B42B7853()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnFailure_A7F272754A56CDF721E29285B42B7853");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnSuccess_1C58A86A453328AE0BEDCB9C9CC5B450
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMer2AchievementComponent_C::OnSuccess_1C58A86A453328AE0BEDCB9C9CC5B450(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnSuccess_1C58A86A453328AE0BEDCB9C9CC5B450");

	Params::Mer2AchievementComponent_C_OnSuccess_1C58A86A453328AE0BEDCB9C9CC5B450 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mer2AchievementComponent.Mer2AchievementComponent_C.OnFailure_1C58A86A453328AE0BEDCB9C9CC5B450
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMer2AchievementComponent_C::OnFailure_1C58A86A453328AE0BEDCB9C9CC5B450(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mer2AchievementComponent_C", "OnFailure_1C58A86A453328AE0BEDCB9C9CC5B450");

	Params::Mer2AchievementComponent_C_OnFailure_1C58A86A453328AE0BEDCB9C9CC5B450 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}

}

