#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PCModeCheat

#include "Basic.hpp"

#include "PCModeCheat_classes.hpp"
#include "PCModeCheat_parameters.hpp"


namespace SDK
{

// Function PCModeCheat.PCModeCheat_C.ExecuteUbergraph_PCModeCheat
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPCModeCheat_C::ExecuteUbergraph_PCModeCheat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PCModeCheat_C", "ExecuteUbergraph_PCModeCheat");

	Params::PCModeCheat_C_ExecuteUbergraph_PCModeCheat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PCModeCheat.PCModeCheat_C.AddText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AI_Wave_C*                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPCModeCheat_C::AddText(class ABP_AI_Wave_C* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PCModeCheat_C", "AddText");

	Params::PCModeCheat_C_AddText Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PCModeCheat.PCModeCheat_C.BndEvt__Button_114_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UPCModeCheat_C::BndEvt__Button_114_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PCModeCheat_C", "BndEvt__Button_114_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PCModeCheat.PCModeCheat_C.ClearText
// (BlueprintCallable, BlueprintEvent)

void UPCModeCheat_C::ClearText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PCModeCheat_C", "ClearText");

	UObject::ProcessEvent(Func, nullptr);
}

}

