#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_Pistol_NoPower

#include "Basic.hpp"

#include "Projectile_Pistol_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_Pistol_NoPower.Projectile_Pistol_NoPower_C
// 0x0000 (0x0528 - 0x0528)
class AProjectile_Pistol_NoPower_C final : public AProjectile_Pistol_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_Pistol_NoPower_C">();
	}
	static class AProjectile_Pistol_NoPower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_Pistol_NoPower_C>();
	}
};
static_assert(alignof(AProjectile_Pistol_NoPower_C) == 0x000008, "Wrong alignment on AProjectile_Pistol_NoPower_C");
static_assert(sizeof(AProjectile_Pistol_NoPower_C) == 0x000528, "Wrong size on AProjectile_Pistol_NoPower_C");

}

