#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_Slide_Skeleton_AnimBlueprint

#include "Basic.hpp"

#include "Prop_Slide_Skeleton_AnimBlueprint_classes.hpp"
#include "Prop_Slide_Skeleton_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function Prop_Slide_Skeleton_AnimBlueprint.Prop_Slide_Skeleton_AnimBlueprint_C.ExecuteUbergraph_Prop_Slide_Skeleton_AnimBlueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UProp_Slide_Skeleton_AnimBlueprint_C::ExecuteUbergraph_Prop_Slide_Skeleton_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Prop_Slide_Skeleton_AnimBlueprint_C", "ExecuteUbergraph_Prop_Slide_Skeleton_AnimBlueprint");

	Params::Prop_Slide_Skeleton_AnimBlueprint_C_ExecuteUbergraph_Prop_Slide_Skeleton_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Prop_Slide_Skeleton_AnimBlueprint.Prop_Slide_Skeleton_AnimBlueprint_C.InitAnim
// (BlueprintCallable, BlueprintEvent)

void UProp_Slide_Skeleton_AnimBlueprint_C::InitAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Prop_Slide_Skeleton_AnimBlueprint_C", "InitAnim");

	UObject::ProcessEvent(Func, nullptr);
}

}

