#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StartingLevel

#include "Basic.hpp"


namespace SDK::Params
{

// Function StartingLevel.StartingLevel_C.ExecuteUbergraph_StartingLevel
// 0x0004 (0x0004 - 0x0000)
struct StartingLevel_C_ExecuteUbergraph_StartingLevel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(StartingLevel_C_ExecuteUbergraph_StartingLevel) == 0x000004, "Wrong alignment on StartingLevel_C_ExecuteUbergraph_StartingLevel");
static_assert(sizeof(StartingLevel_C_ExecuteUbergraph_StartingLevel) == 0x000004, "Wrong size on StartingLevel_C_ExecuteUbergraph_StartingLevel");
static_assert(offsetof(StartingLevel_C_ExecuteUbergraph_StartingLevel, EntryPoint) == 0x000000, "Member 'StartingLevel_C_ExecuteUbergraph_StartingLevel::EntryPoint' has a wrong offset!");

}

