#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerifyGame

#include "Basic.hpp"

#include "VerifyGame_classes.hpp"
#include "VerifyGame_parameters.hpp"


namespace SDK
{

// Function VerifyGame.VerifyGame_C.ExecuteUbergraph_VerifyGame
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVerifyGame_C::ExecuteUbergraph_VerifyGame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerifyGame_C", "ExecuteUbergraph_VerifyGame");

	Params::VerifyGame_C_ExecuteUbergraph_VerifyGame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerifyGame.VerifyGame_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UVerifyGame_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerifyGame_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerifyGame.VerifyGame_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UVerifyGame_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerifyGame_C", "PreConstruct");

	Params::VerifyGame_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerifyGame.VerifyGame_C.ApplyText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Text_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UTextBlock*                       TextBox                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ApplySize                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UVerifyGame_C::ApplyText(const class FString& Text_0, class UTextBlock* TextBox, bool ApplySize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerifyGame_C", "ApplyText");

	Params::VerifyGame_C_ApplyText Parms{};

	Parms.Text_0 = std::move(Text_0);
	Parms.TextBox = TextBox;
	Parms.ApplySize = ApplySize;

	UObject::ProcessEvent(Func, &Parms);
}

}

